# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgencyName', models.CharField(max_length=75)),
                ('BusinessType', models.CharField(max_length=30)),
                ('PrimaryContactFN', models.CharField(max_length=30)),
                ('PrimaryContactLN', models.CharField(max_length=30)),
                ('ContactTitle', models.CharField(max_length=30)),
                ('ContactEmail', models.EmailField(max_length=254)),
                ('DirectLine', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('HQAddress', models.CharField(max_length=30)),
                ('HQAddress2', models.CharField(max_length=30)),
                ('HQCity', models.CharField(max_length=30)),
                ('HQState', models.CharField(max_length=30)),
                ('HQZip', models.CharField(max_length=15)),
                ('HQCountry', models.CharField(max_length=30)),
                ('Differentiator', models.TextField(max_length=900)),
                ('KeyContactFN', models.CharField(blank=True, max_length=35)),
                ('KeyContactLN', models.CharField(blank=True, max_length=35)),
                ('KeyContactEmail', models.EmailField(blank=True, max_length=35)),
                ('KeyContactPhone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('tags', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
