# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 14:17
from __future__ import unicode_literals

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Isure', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directory',
            options={'verbose_name_plural': 'Directory'},
        ),
        migrations.AlterField(
            model_name='directory',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
