# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Isure', '0002_auto_20161022_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directory',
            old_name='tags',
            new_name='tagsX',
        ),
    ]
