# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Isure', '0003_auto_20161022_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directory',
            old_name='tagsX',
            new_name='tags',
        ),
    ]
