# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isure', '0004_auto_20161023_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='HQAddress2',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
