# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 18:40
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Isure', '0005_auto_20161023_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='favs',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('blue', 'Blue'), ('green', 'Green'), ('black', 'Black')], default='', max_length=16),
            preserve_default=False,
        ),
    ]
