# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Isure', '0006_directory_favs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eventtext', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuickLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Linktype', models.CharField(choices=[('pdf', 'PDF'), ('event', 'Event')], max_length=10)),
                ('filename', models.CharField(blank=True, max_length=50)),
                ('eventname', models.CharField(blank=True, max_length=50)),
                ('event_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Isure.Event')),
            ],
        ),
        migrations.RemoveField(
            model_name='directory',
            name='favs',
        ),
    ]
