# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isure', '0009_auto_20161025_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quicklinks',
            name='eventname',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
