# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isure', '0011_auto_20161025_0428'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostDate', models.DateField()),
                ('Blurb', models.CharField(max_length=250)),
                ('filename', models.ImageField(upload_to='Docs')),
                ('publish', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Press Release',
            },
        ),
    ]
