# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Isure', '0012_pressrel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pressrel',
            old_name='Blurb',
            new_name='plurb',
        ),
        migrations.RenameField(
            model_name='pressrel',
            old_name='PostDate',
            new_name='postDate',
        ),
    ]
