# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Isure', '0013_auto_20161029_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pressrel',
            old_name='plurb',
            new_name='blurb',
        ),
    ]
