# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isure', '0017_auto_20161031_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressrel',
            name='filename',
            field=models.FileField(upload_to='Docs'),
        ),
    ]
