# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isure', '0019_directory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='Differentiator',
            field=models.TextField(max_length=2000),
        ),
    ]
