# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isure', '0020_auto_20161031_0429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commercials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Commercial Lines',
            },
        ),
        migrations.CreateModel(
            name='Personals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Personal Lines',
            },
        ),
        migrations.AddField(
            model_name='directory',
            name='url',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='directory',
            name='Differentiator',
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='directory',
            name='Image',
            field=models.FileField(blank=True, upload_to='Pics'),
        ),
        migrations.AddField(
            model_name='directory',
            name='commercialsLines',
            field=models.ManyToManyField(to='Isure.Commercials'),
        ),
        migrations.AddField(
            model_name='directory',
            name='personalsLines',
            field=models.ManyToManyField(to='Isure.Personals'),
        ),
    ]
