# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Isure', '0021_auto_20161031_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directory',
            old_name='commercialsLines',
            new_name='commercialLines',
        ),
        migrations.RenameField(
            model_name='directory',
            old_name='personalsLines',
            new_name='personalLines',
        ),
    ]
