# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isure', '0022_auto_20161031_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='commercialLines',
            field=models.ManyToManyField(blank=True, to='Isure.Commercials'),
        ),
        migrations.AlterField(
            model_name='directory',
            name='personalLines',
            field=models.ManyToManyField(blank=True, to='Isure.Personals'),
        ),
        migrations.AlterField(
            model_name='directory',
            name='url',
            field=models.CharField(blank=True, max_length=175),
        ),
    ]
