# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isure', '0023_auto_20161101_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pagesource', models.CharField(max_length=50)),
                ('receivedfrom', models.CharField(max_length=75)),
                ('sentto', models.CharField(max_length=75)),
                ('content', models.TextField()),
            ],
        ),
    ]
