# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 23:10
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isure', '0024_emailcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='HQLat',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00000'), max_digits=10),
        ),
        migrations.AddField(
            model_name='directory',
            name='HQLong',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00000'), max_digits=11),
        ),
    ]
