# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 23:07
from __future__ import unicode_literals

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Isure', '0025_auto_20161106_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=500),
        ),
    ]
