# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 02:17
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isure', '0026_auto_20161118_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='AMS',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='directory',
            name='BenePct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4),
        ),
        migrations.AddField(
            model_name='directory',
            name='CRM',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='directory',
            name='CommPct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4),
        ),
        migrations.AddField(
            model_name='directory',
            name='PersPct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4),
        ),
        migrations.AddField(
            model_name='directory',
            name='Revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
