# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 03:30
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isure', '0027_auto_20161118_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='AMS',
            field=models.CharField(blank=True, max_length=25, verbose_name='Account Mgmt System '),
        ),
        migrations.AlterField(
            model_name='directory',
            name='BenePct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, verbose_name='Benefits Percent'),
        ),
        migrations.AlterField(
            model_name='directory',
            name='CRM',
            field=models.CharField(blank=True, max_length=25, verbose_name='Customer Relationship Mgmt'),
        ),
        migrations.AlterField(
            model_name='directory',
            name='CommPct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, verbose_name='Commercial Percent'),
        ),
        migrations.AlterField(
            model_name='directory',
            name='PersPct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, verbose_name='Persaonal Percent'),
        ),
        migrations.AlterField(
            model_name='directory',
            name='Revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11),
        ),
    ]
