# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 09:46
from __future__ import unicode_literals

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Isure', '0029_accesslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=1000),
        ),
    ]
