# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isure', '0030_auto_20161130_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='awards1',
            field=models.CharField(blank=True, max_length=500, verbose_name='Top Awards1'),
        ),
        migrations.AddField(
            model_name='directory',
            name='awards2',
            field=models.CharField(blank=True, max_length=500, verbose_name='Top Awards2'),
        ),
        migrations.AddField(
            model_name='directory',
            name='awards3',
            field=models.CharField(blank=True, max_length=500, verbose_name='Top Awards3'),
        ),
        migrations.AddField(
            model_name='directory',
            name='employees',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Employees'),
        ),
        migrations.AddField(
            model_name='directory',
            name='goals1',
            field=models.CharField(blank=True, max_length=500, verbose_name='Top Goals1'),
        ),
        migrations.AddField(
            model_name='directory',
            name='goals2',
            field=models.CharField(blank=True, max_length=500, verbose_name='Top Goals2'),
        ),
        migrations.AddField(
            model_name='directory',
            name='goals3',
            field=models.CharField(blank=True, max_length=500, verbose_name='Top Goals3'),
        ),
        migrations.AddField(
            model_name='directory',
            name='principals',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Principals'),
        ),
    ]
