# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isure', '0033_auto_20161201_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='HQAddress',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='directory',
            name='HQAddress2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='directory',
            name='HQCity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='directory',
            name='PrimaryContactFN',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='directory',
            name='PrimaryContactLN',
            field=models.CharField(max_length=40),
        ),
    ]
